-- MySQL Script generated by MySQL Workbench
-- ter 28 mar 2023 20:53:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema fpa_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fpa_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS fpa_database DEFAULT CHARACTER SET utf8 ;
USE fpa_database ;

-- -----------------------------------------------------
-- Table `fpa_database`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario (
  idUsuario INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) NOT NULL,
  prontuario VARCHAR(45) NOT NULL UNIQUE,
  senha VARCHAR(45) NOT NULL,
  cpf VARCHAR(45) NOT NULL,
  cargo VARCHAR(1) DEFAULT 'p',
  tempoCampus INT,
  tempoExp INT,
  tempoProfissional INT,
  tempoInstituicao INT,
  nivelCarreira INT,
  idade INT,
  PRIMARY KEY (idUsuario))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `fpa_database`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cursos (
  idCurso VARCHAR(10) NOT NULL,
  nomeCurso VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `fpa_database`.`componentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS componentes (
  idComponentes VARCHAR(10) NOT NULL,
  nomeMateria VARCHAR(45) NOT NULL,
  cursos_idCurso VARCHAR(10) NOT NULL,
  periodo VARCHAR(15), -- M=Manhã, T=Tarde, N=Noturno
  horasSemanais INT,
  usuario_atribuidoPara INT,
  PRIMARY KEY (`idComponentes`),
  CONSTRAINT fk_componentes_cursos
    FOREIGN KEY (cursos_idCurso)
    REFERENCES fpa_database.cursos (idCurso)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_componentes_usuario
    FOREIGN KEY (usuario_atribuidoPara)
    REFERENCES fpa_database.usuario (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `fpa_database`.`horario`
-- -----------------------------------------------------
CREATE Table IF NOT EXISTS horario (
  componente_idComponentes VARCHAR(10) NOT NULL,
  idHorario INT NOT NULL AUTO_INCREMENT,
  diaSemana VARCHAR(45) NOT NULL,
  horaInicio TIME NOT NULL,
  horaFim TIME NOT NULL,
  PRIMARY KEY(`idHorario`),
  CONSTRAINT fk_horario_componentes
    FOREIGN KEY (componente_idComponentes)
    REFERENCES fpa_database.componentes (idComponentes)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fpa_database`.`preferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS preferencia (
  idPreferencia INT NOT NULL AUTO_INCREMENT,
  usuario_idUsuario INT NOT NULL,
  componentes_idComponentes VARCHAR(10) NOT NULL,
  prioridade INT NOT NULL,
  PRIMARY KEY (idPreferencia),
  CONSTRAINT fk_preferencia_usuario
    FOREIGN KEY (usuario_idUsuario)
    REFERENCES fpa_database.usuario (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_preferencia_componentes
    FOREIGN KEY (componentes_idComponentes)
    REFERENCES fpa_database.componentes (idComponentes)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- POPULANDO DATABASE --
-- USUARIO --
insert into usuario(nome, prontuario, senha, cpf, cargo) value('João','12345','12345','6789','c');
insert into usuario(nome, prontuario, senha, cpf, cargo) value('Andre','345678','12345','12345','p');
insert into usuario(nome, prontuario, senha, cpf, cargo) value('Moana','67890','67890','67890','p');

-- CURSOS --

insert into cursos(idCurso, nomeCUrso) value
         ('EM', 'Engrenharia Mecânica'),
         ('ADS', 'Análise e Desenvolvimento de Sistemas'),
         ('TII', 'Técnico Integrado em Informática'),
         ('TIM', 'Técnico Integrado em Mecânica'),
         ('TI', 'Técnico Informática'),
         ('TM', 'Técnico Mecatrônica'),
         ('TSI', 'Tecnólogo para Sistema da Internet'),
         ('LM', 'Licenciatura em Matemática');

-- COMPONENTE --
insert into componentes(idComponentes, nomeMateria, cursos_idCurso, periodo, horasSemanais) value('ISO', 'Introdução a Sistemas Operacionais', 'TSI', 'Noite', 4);
insert into componentes(idComponentes, nomeMateria, cursos_idCurso, periodo, horasSemanais) value('IPW', 'Introdução a Programção Web', 'TI', 'Tarde', 8);
insert into componentes(idComponentes, nomeMateria, cursos_idCurso, periodo, horasSemanais) value('DAC', 'Desenho Assistido por Computador', 'TSI', 'Manhã', 4);

-- HORARIO --
insert into horario(componente_idComponentes, diaSemana, horaInicio, horaFim) value('ISO', 'quarta', '19:00', '22:35');
insert into horario(componente_idComponentes, diaSemana, horaInicio, horaFim) value('IPW', 'terça', '19:00', '22:35');
insert into horario(componente_idComponentes, diaSemana, horaInicio, horaFim) value('IPW', 'sexta', '19:00', '22:35');
insert into horario(componente_idComponentes, diaSemana, horaInicio, horaFim) value('DAC', 'terça', '12:35', '14:15');

-- ATRIBUIDO -- 
-- insert into atribuido(componentes_idComponentes, usuario_idUsuario) value('ISO',1);
-- insert into atribuido(componentes_idComponentes, usuario_idUsuario) value('IPW',2);