-- MySQL Script generated by MySQL Workbench
-- ter 28 mar 2023 20:53:39
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema fpa_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fpa_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS fpa_database DEFAULT CHARACTER SET utf8 ;
USE fpa_database ;

-- -----------------------------------------------------
-- Table `fpa_database`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario (
  idUsuario INT NOT NULL AUTO_INCREMENT,
  nome VARCHAR(45) NOT NULL,
  prontuario VARCHAR(45) NOT NULL UNIQUE,
  senha VARCHAR(45) NOT NULL,
  cpf VARCHAR(45) NOT NULL,
  cargo VARCHAR(1) DEFAULT 'p',
  tempoCampus INT,
  tempoExp INT,
  tempoProficional INT,
  tempoInstuicao INT,
  nivelCarreira INT,
  idade INT,
  PRIMARY KEY (idUsuario))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fpa_database`.`componentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS componentes (
  idComponentes INT NOT NULL AUTO_INCREMENT,
  nomeMateria VARCHAR(45) NOT NULL,
  diaHorario DATETIME NOT NULL,
  curso VARCHAR(45),
  horasSemanais INT,
  PRIMARY KEY (`idComponentes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fpa_database`.`preferencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS preferencia (
  idPreferencia INT NOT NULL AUTO_INCREMENT,
  professor_idProfessor INT NOT NULL,
  componentes_idComponentes INT NOT NULL,
  prioridade VARCHAR(45) NOT NULL,
  PRIMARY KEY (idPreferencia),
  CONSTRAINT fk_preferencia_professor
    FOREIGN KEY (professor_idProfessor)
    REFERENCES fpa_database.usuario (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_preferencia_componentes1
    FOREIGN KEY (componentes_idComponentes)
    REFERENCES fpa_database.componentes (idComponentes)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `fpa_database`.`atribuido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS atribuido (
  idAtribuido INT NOT NULL AUTO_INCREMENT,
  componentes_idComponentes INT NOT NULL,
  user_idUsuario INT NOT NULL,
  PRIMARY KEY (idAtribuido),
  CONSTRAINT fk_atribuido_componentes1
    FOREIGN KEY (componentes_idComponentes)
    REFERENCES fpa_database.componentes (idComponentes)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_atribuido_usuario1
    FOREIGN KEY (user_idUsuario)
    REFERENCES fpa_database.usuario (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- POPULANDO DATABASE --
-- USUARIO --
insert into usuario(nome, prontuario, senha, cpf, cargo) value('João','12345','12345','6789','c');
insert into usuario(nome, prontuario, senha, cpf, cargo) value('Andre','345678','12345','12345','p');
insert into usuario(nome, prontuario, senha, cpf, cargo) value('Moana','67890','67890','67890','p');

-- COMPONENTES --
insert into componentes(nomeMateria, diaHorario, curso, horasSemanais) value('ISO - Introdução a Sistemas Operacionais', '2023-02-13 19:00:00', 'Tec info noturno', 4);
insert into componentes(nomeMateria, diaHorario, curso, horasSemanais) value('IPW - Introdução a Programção Web', '2023-02-15 12:35:00', 'Int info Tarde', 4);
insert into componentes(nomeMateria, diaHorario, curso, horasSemanais) value('DAC - Desenho Assistido por Computador', '2023-02-16 14:25:00', 'Int mec Tarde', 2);

-- PREFERENCIA -- 
-- insert into preferencia(professor_idProfessor, componentes_idComponentes, prioridade) value('')

